# -*- coding: utf-8 -*-
"""Hashemi-np-answers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17pFxNSxQXm_EGnogqjjIVjWPzDku-NMq
"""

import numpy as np

np.zeros(10)

np.zeros((2,2))

np.ones(10)

a = np.ones(10)

a *=5

a

np.full(10,5.0)

np.arange(10,51,2)

matrix = np.arange(9).reshape(3,3)

matrix.shape

j = np.identity(3)

j.shape

np.random.rand()

np.random.randn(25)

matrix = np.arange(0.01,1.01,0.01).reshape(10,10)

matrix

matrix.shape

matrix.ndim

linspace = np.linspace(0,1,20)

linspace

0.10526316- 0.15789474

# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

h = mat[2:,1:]

h

r =mat[3][4]

r

r = mat[:3,1:2]
r

g = mat[-2:]
g

np.sum(mat)

mat.sum()

d = np.std(mat)
d

mat.sum(axis=0)

np.sum(mat, axis=0)

np.random.seed(44)
np.random.rand(5)